#!/bin/sh

[[ $# -ne 1 ]] && {
    echo "Error. No file specified." 1>&2
    exit 99
}

dirs=(
    /u/sciteam/bernardi/DecaAla.run.2
    /u/sciteam/bernardi/DecaAla.run.3
    /u/sciteam/bernardi/DecaAla.run
    /u/sciteam/cardosod/GSAFold/RunBW/1A13_s500K_r400K/FinalConformations
    /u/sciteam/cardosod/GSAFold/RunBW/1L2Y_s250K_r400K/FinalConformations
    /u/sciteam/cardosod/GSAFold/RunBW/1VII_s250K_r400K/FinalConformations
    /u/sciteam/chen4/invrender/128_128/debug_train
    /u/sciteam/frasson/OLAM/run4.0t-LowR/history
    /u/sciteam/jcurtis2/wrf_test/wrf_partmc-3D/trunk/test/em_scm_xy/out
    /u/sciteam/jfunk/olam/run/history
    /u/system/darshan/orphan/rdong
)

head -1 "$1"
for d in "${dirs[@]}"; do
    fgrep "$d" "$1" | head -1
done
